id: onconova.fhir
canonical: http://onconova.github.io/fhir
fhirVersion: 4.0.1
name: Onconova
title: "Onconova Implementation Guide"
status: active
publisher:
  name: Onconova
  url: http://onconova.github.io/docs
description: "Onconova is an open-source data platform aiming to enable reliable, structured data collection and analysis in precision oncology. Our goal is to support clinical research and development through interoperable, accessible software."
license: MIT
version: 0.2.0
copyrightYear: 2025+
releaseLabel: ci-build
dependencies:
  hl7.fhir.uv.genomics-reporting: 
    version: 2.0.0
    id: hl7fhiruvgenomicsreporting
  hl7.fhir.us.core: 
    version: 6.1.0
    id: hl7fhiruscore
  hl7.fhir.us.mcode:
    id: mcode
    uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
    version: 4.0.0
menu:
  Home: index.html
  Conformance: CapabilityStatement-onconova-capability-statement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html
  Onconova Documentation: https://onconova.github.io/docs/latest/
instanceOptions:
  manualSliceOrdering: true
parameters:
    no-ig-database: 'true'
    excludexml: 'true'
    excludettl: 'true'
    wantGen-ttl: 'false'
    wantGen-ttl-html: 'false'
    wantGen-xml: 'false'
    wantGen-xml-html: 'false'